version: "2"
services:

   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 11111
       MYSQL_DATABASE: provider
       MYSQL_USER: provider
       MYSQL_PASSWORD: provider

   provider_web_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
volumes:
    db_data:

