version: "2"
services:

   provider_web_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
   admin_web_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
   app_client_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
       
   paygateway_server_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
       
   repo_server_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider

   scheduler_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider

   ticket_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8080:8080"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider       
  
volumes:
    db_data:
