version: "2"
services:

   provider_web_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "18083:18083"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
   admin_web_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "18089:18089"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
   app_client_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "18089:18089"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
       
   paygateway_server_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "18882:18882"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider
       
   repo_server_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "8081:8081"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider

   scheduler_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "18098:18098"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider

   ticket_tomcat:
     depends_on:
       - db
     image: tomcat:8-jre8
     ports:
       - "18580:18580"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: provider
       WORDPRESS_DB_PASSWORD: provider       
  
volumes:
    db_data:
